### ISSUE TITLE
Error loading module after CW Control Update

### ISSUE THREAD

**Issue by MordyT** [johnduprey/CWCAutomateDiagnostics#6]
Upgraded from 20,2 to 20.3. Have had the module running for a year+ with no issues - excellent module.

Getting the error in the screenshot. As a test, uninstalled and reinstalled the module, error did not change.
![error](https://user-images.githubusercontent.com/779947/80907183-3ea54880-8cda-11ea-9648-0adcc28edeb8.png)

**Comment by MordyT** [comment]
Welp, I'm a little trigger happy.

I downloaded the latest code from Github and did a manual update - issue is resolved.

**Comment by MordyT** [comment]
I'm going to re-open this for 2 reasons...

1) The sidebar display has changed - it's missing most of the information
2) CW marketplace claims and update is now available, but it's the old version

![display](https://user-images.githubusercontent.com/779947/80908235-ea9f6180-8ce3-11ea-9b0e-139ee970926b.png)

**Comment by gherbstman** [comment]
The CW marketplace version still fails with the new 20.3 version of Control. Status: Load Error

**Comment by JohnDuprey** [comment]
This should have been resolved on the build published May 7th
